# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FLOAPP' do
    pod 'RESideMenu'
    pod 'SDWebImage'
    pod 'MBProgressHUD'
    pod 'YYKit'
    pod 'FMDB'
    pod 'AFNetworking'
    pod 'MJRefresh'
    pod 'BaiduMapKit'
    pod 'FLEX', '~> 2.0'
    pod 'Masonry'
    pod 'MQTTClient'

    # ReactNative
    # 'node_modules'目录一般位于根目录中
    # 但是如果你的结构不同，那你就要根据实际路径修改下面的`:path`
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'Core',
        'RCTText',
        'RCTNetwork',
        'RCTWebSocket', # 这个模块是用于调试功能的
        # 在这里继续添加你所需要的模块
        'RCTAnimation',
        'RCTCameraRoll',
        'RCTGeolocation',
        'RCTImage',
        'RCTSettings',
        'RCTLinkingIOS',
        'RCTTest'
    ]
    # 如果你的RN版本 >= 0.42.0，请加入下面这行
    pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
    end
end
